# docker-compose.prod.yml for a simple Nginx service.
# This is designed for local testing of the container that will be deployed to Claw Cloud.

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: simple-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    # Resource limits are recommended for production
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'